"""empty message

Revision ID: 3b9a0793b165
Revises: 8e7f56ea2724
Create Date: 2026-01-18 11:33:32.158351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9a0793b165'
down_revision = '8e7f56ea2724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favoritesCharacter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritesCharacter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favoritesCharacter_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favoritesCharacter_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favoritesCharacter_pkey')
    )
    op.drop_table('favorites_character')
    # ### end Alembic commands ###
